version: '3.8'  

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  
      - "4572:4572"  
    environment:
      - SERVICES=s3 
      - DEBUG=1     
    volumes:
      - "/tmp/localstack:/tmp/localstack"  